version: '3.9'

services:
  db-postgresql:
    image: postgres:15.1
    ports:
      - "5999:5432"
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile.deploy
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://user:secret@db-postgresql:5999/testing
    env_file:
      - envs/.env.docker
    volumes:
      - .:/application

  test:
    build:
      context: .
      dockerfile: deployments/tests/Dockerfile.test
    env_file:
      - envs/.env.docker.testing
    volumes:
      - .:/application